## 00. Fundamentals

[Resource notebook](https://www.learnpytorch.io/00_pytorch_fundamentals/)

In [101]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)
print(torch.cuda.is_available())
# print(torch.rand(2,3).cuda())
# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

2.0.1+cpu
False


#### Make 
> **Scalar**
> **Vector**
> **MATRIX**
> **TENSOR**

In [102]:
# Scalar
scalar = torch.tensor(7)
print(scalar.ndim)
print(scalar.item())  # give back the number as python (int)


0
7


In [103]:
# Vector
vector = torch.tensor([7, 7])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [104]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX.ndim)
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX.shape)

2
tensor([7, 8])
tensor([ 9, 10])
torch.Size([2, 2])


In [105]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


#### Random Tensors

**why random tensors?** random tensors are important because the way many neural networks  
 learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

****Start with Random numbers > look at data > update random numbers > look at data > update random numbers**

In [106]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)

In [107]:
print(random_tensor.ndim)
print(random_tensor.shape)
random_tensor

2
torch.Size([3, 4])


tensor([[0.5066, 0.8066, 0.9452, 0.4211],
        [0.0586, 0.8153, 0.6178, 0.0553],
        [0.3393, 0.2781, 0.0106, 0.4998]])

In [108]:
# random tensor similar to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [109]:
t = torch.rand([2, 2])
t2 = torch.rand(size=(2, 2))

In [110]:
t

tensor([[0.3538, 0.2011],
        [0.2430, 0.3119]])

In [111]:
t2

tensor([[0.8338, 0.9722],
        [0.2537, 0.6987]])

In [112]:
# zeros
zeros = torch.zeros((3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [113]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [114]:
# Ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [115]:
ones.dtype

torch.float32

In [116]:
# Creating a range of tensors and tensors-like

one_to_ten = torch.arange(start=0, end=11, step=1)

In [117]:
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
tensors_like = torch.zeros_like(input=one_to_ten)

In [119]:
tensors_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## datatypes

**Note: Tensor datatypes is one of the 3 big errors with PyTorch**
1. Tensors not tight datatype
2. Tensors not tight shape
3. Tensors not on the right device

In [120]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)

In [121]:
float_32_tensor.dtype

torch.float32

In [122]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

In [123]:
float_32_tensor.dtype

torch.float16

In [124]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)

In [125]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [126]:
m = float_16_tensor * float_32_tensor

In [127]:
m.dtype

torch.float32

In [128]:
float_32_tensor = float_16_tensor.type(torch.int32)

In [129]:
float_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [130]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### how to check information to solve bugs

In [131]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6920, 0.9208, 0.5173, 0.5890],
        [0.0174, 0.8011, 0.0221, 0.5263],
        [0.8960, 0.9418, 0.4756, 0.3617]])

In [132]:
print(some_tensor)
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"device tensor is on: {some_tensor.device}")


tensor([[0.6920, 0.9208, 0.5173, 0.5890],
        [0.0174, 0.8011, 0.0221, 0.5263],
        [0.8960, 0.9418, 0.4756, 0.3617]])
datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
device tensor is on: cpu


In [133]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [134]:
tensor * 10

tensor([10, 20, 30])

In [135]:
tensor - 10

tensor([-9, -8, -7])

In [136]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [137]:
torch.mul(tensor, 10)
torch.add(tensor, 10)

tensor([11, 12, 13])

# multiplication

In [138]:
# Element wise
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [139]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [140]:
v = 0
for i in range(len(tensor)):
    v += tensor[i] * tensor[i]
print(v)

tensor(14)


In [141]:
tensor.shape

torch.Size([3])

In [142]:
tensor = torch.rand((1, 4))

In [143]:
tensor2 = tensor.reshape(-1, 1)

In [144]:
tensor2.shape

torch.Size([4, 1])

In [145]:
torch.matmul(tensor, tensor2)

tensor([[1.0958]])

In [146]:
torch.matmul(tensor, tensor.T)

tensor([[1.0958]])

In [147]:
tensor.flatten()

tensor([0.7677, 0.4023, 0.3478, 0.4729])

In [148]:
tensor.shape

torch.Size([1, 4])

In [149]:
tensor @ tensor2

tensor([[1.0958]])

In [150]:
# Shape for matrix

tensorA = torch.tensor([[1, 2], [3, 4], [5, 6]])

tensorB = torch.tensor([[7, 10], [8, 11], [9, 12]])

torch.mm(tensorA, tensorB.T)  # torch.mm = torch.matmul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### to fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose

### A **transpose** switches the axes or dimensions of a given tensor

In [151]:
tensorB.T, tensorB

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

# mean max min sum(tensor aggregation)

In [161]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [168]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [167]:
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [166]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [170]:
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

In [172]:
# find the positional
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [173]:
x[0], x[9]

(tensor(0), tensor(90))

# Reshaping, Stacking, Squeezing and unsqueezing tensors

### **reshaping**: reshape an input tensor to a defined shape
### **view**: return a view of an input tensor of certain shape but keep the same memory as the original tensor
### **stacking**: combine multiple tensors on top of each other (vstack) or side by side(hstack)
### **squeeze**: removes all '1' dimensions from a tensor
### **unsqueeze**: add a '1' dimension to a target tensor.
### **permute**: return a view of the input with dimensions permuted(swapped) in a certain way.

In [198]:
x = torch.arange(1, 10)
x = x.type(torch.float32)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [199]:
x_1 = x.reshape(1, 9)
x, x_1, x_1.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]))

In [236]:
x_2 = x.view(1, 9)
x_2[0, 0] = 10
x, x_2, x_2.shape

(tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]),
 tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 torch.Size([1, 9]))

In [213]:
x_stacked = torch.stack([x, x, x, x])
x_stacked1 = torch.stack([x, x, x, x], dim=1)
x_stacked.shape, x_stacked1.shape

(torch.Size([4, 9]), torch.Size([9, 4]))

In [211]:
x_stacked = torch.hstack([x, x, x, x])
x_stacked1 = torch.vstack([x, x, x, x])
x_stacked.shape, x_stacked1.shape

(torch.Size([36]), torch.Size([4, 9]))

In [218]:
x_1.shape, x_1.squeeze().shape

(torch.Size([1, 9]), torch.Size([9]))

In [219]:
x_1, x_1.squeeze()

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [234]:
x_1.unsqueeze(dim=1).shape, x_1.unsqueeze(dim=2).shape, x_1.unsqueeze(dim=0).shape

(torch.Size([1, 1, 9]), torch.Size([1, 9, 1]), torch.Size([1, 1, 9]))

In [235]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [237]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [240]:
x[0], x[0, 2, 0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor(7))

In [242]:
x[0][0], x[0][0][0]

(tensor([1, 2, 3]), tensor(1))

In [244]:
x[0, :, 0]

tensor([1, 4, 7])

In [245]:
x[:, 1, 1], x[0, 1, 1]  # important

(tensor([5]), tensor(5))

# Numpy

In [261]:
import numpy as np

array = np.arange(1., 8., 1.0)
tensor = torch.from_numpy(array)  # warning: it will send numpy dtype mostly float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [262]:
array = array + 1
array[0] = 100
array, tensor

(array([100.,   3.,   4.,   5.,   6.,   7.,   8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [264]:
tensor = torch.ones(7)
array = tensor.numpy()
tensor, array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [265]:
tensor = tensor + 1
tensor, array

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility ( trying to take random out of random)

to reduce the randomness in neural network and pytorch come the concept of **random seed**
essentially what the random seed does is "flavour" the randomness.

In [272]:
import torch

random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_b == random_tensor_a)

tensor([[0.9023, 0.7760, 0.2694, 0.9547],
        [0.1822, 0.8206, 0.4911, 0.3487],
        [0.4477, 0.3977, 0.9378, 0.9994]])
tensor([[0.5508, 0.8449, 0.7012, 0.8528],
        [0.4914, 0.9298, 0.3310, 0.6889],
        [0.8756, 0.7816, 0.9540, 0.8593]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [302]:
random_seed = 42
torch.manual_seed(random_seed)
random_tensor_c = torch.rand(3, 4)

torch.manual_seed(random_seed)
random_tensor_d = torch.rand(3, 4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### 1. Getting a GPU


In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
torch.cuda.device_count()

1

In [4]:
tensor = torch.tensor([1,2,3])

tensor.device

device(type='cpu')

In [8]:
tensor = tensor.to("cuda") # or tensor.to(device)

In [9]:
tensor.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [10]:
tensor_back = tensor.cpu()

In [11]:
tensor_back.numpy()
tensor.cpu().numpy()

array([1, 2, 3], dtype=int64)